sidebar:
  
  entries:
  - title: ようこそ！
    url: "/index.html"
  - title: 2021 年です
    entries:
    - title: Astra Control Center のドキュメント
      url: "/astra_control_center.html"
    - title: デフォルトブランチの名前が main に変更されました
      url: "/default-branch-rename.html"
  - title: 2020 年
    entries:
    - title: NetApp HCI ドキュメントの更新
      url: "/hci-update.html"
    - title: PDF をダウンロードします
      url: "/pdfs.html"
    - title: ユーザエクスペリエンスの向上
      url: "/look-and-feel.html"
    - title: ONTAP System Manager のドキュメント
      url: "/ontap-system-manager.html"
    - title: Cloud Compliance のドキュメント
      url: "/cloud-compliance.html"
    - title: ONTAP Select のドキュメント
      url: "/ontap-select.html"
  - title: 2019 年
    entries:
    - title: NetApp HCI クラウドサービスおよびソリューション用のドキュメント
      url: "/hci.html"
    - title: スタイルガイドおよび構文リファレンス
      url: "/style-and-syntax.html"
    - title: SaaS Backup for Salesforce のドキュメント
      url: "/salesforce.html"
    - title: Active IQ のドキュメント
      url: "/active-iq.html"
    - title: 新しいページの RSS フィード
      url: "/rss.html"
    - title: Cloud Tiering のドキュメント
      url: "/cloud-tiering.html"
    - title: 貢献者の GitHub アバター
      url: "/avatars.html"
  - title: 2018 年
    entries:
    - title: 構文の強調表示
      url: "/syntax.html"
    - title: ページレベルのナビゲーション
      url: "/navigation.html"
    - title: Converged Systems Advisor 用のドキュメント
      url: "/converged-systems-advisor.html"
    - title: ドキュメントの変更を要求する新しい方法
      url: "/request-doc-changes.html"
    - title: Cloud Insights のドキュメント
      url: "/cloud-insights.html"
    - title: Cloud Volumes ONTAP のドキュメント
      url: "/cloud-volumes-ontap.html"
    - title: Cloud Volumes Service for AWS のドキュメント
      url: "/cloud-volumes-service.html"
    - title: ドキュメント：「 SaaS Backup for Office 365
      url: "/office365.html"
    - title: GitHub に NetApp のドキュメントを導入しました
      url: "/introduction.html"
